//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FileStoreModel", "FK_ApplicationEmailAccount_ApplicationDefinition", "ApplicationDefinition", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Snovaspace.Util.FileDataStore.ApplicationDefinition), "ApplicationEmailAccount", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Snovaspace.Util.FileDataStore.ApplicationEmailAccount), true)]
[assembly: EdmRelationshipAttribute("FileStoreModel", "FK_ApplicationEmailAttachment_ApplicationEmail", "ApplicationEmail", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Snovaspace.Util.FileDataStore.ApplicationEmail), "ApplicationEmailAttachment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Snovaspace.Util.FileDataStore.ApplicationEmailAttachment), true)]
[assembly: EdmRelationshipAttribute("FileStoreModel", "FK_ApplicationEmail_ApplicationEmailAccount", "ApplicationEmailAccount", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Snovaspace.Util.FileDataStore.ApplicationEmailAccount), "ApplicationEmail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Snovaspace.Util.FileDataStore.ApplicationEmail), true)]
[assembly: EdmRelationshipAttribute("FileStoreModel", "FK_ApplicationEmailEvent_ApplicationEmail", "ApplicationEmail", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Snovaspace.Util.FileDataStore.ApplicationEmail), "ApplicationEmailEvent", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Snovaspace.Util.FileDataStore.ApplicationEmailEvent), true)]

#endregion

namespace Snovaspace.Util.FileDataStore
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FileStoreEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FileStoreEntities object using the connection string found in the 'FileStoreEntities' section of the application configuration file.
        /// </summary>
        public FileStoreEntities() : base("name=FileStoreEntities", "FileStoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FileStoreEntities object.
        /// </summary>
        public FileStoreEntities(string connectionString) : base(connectionString, "FileStoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FileStoreEntities object.
        /// </summary>
        public FileStoreEntities(EntityConnection connection) : base(connection, "FileStoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserFileContent> UserFileContents
        {
            get
            {
                if ((_UserFileContents == null))
                {
                    _UserFileContents = base.CreateObjectSet<UserFileContent>("UserFileContents");
                }
                return _UserFileContents;
            }
        }
        private ObjectSet<UserFileContent> _UserFileContents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BlockedEmail> BlockedEmails
        {
            get
            {
                if ((_BlockedEmails == null))
                {
                    _BlockedEmails = base.CreateObjectSet<BlockedEmail>("BlockedEmails");
                }
                return _BlockedEmails;
            }
        }
        private ObjectSet<BlockedEmail> _BlockedEmails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UsageAudit> UsageAudits
        {
            get
            {
                if ((_UsageAudits == null))
                {
                    _UsageAudits = base.CreateObjectSet<UsageAudit>("UsageAudits");
                }
                return _UsageAudits;
            }
        }
        private ObjectSet<UsageAudit> _UsageAudits;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ApplicationDefinition> ApplicationDefinitions
        {
            get
            {
                if ((_ApplicationDefinitions == null))
                {
                    _ApplicationDefinitions = base.CreateObjectSet<ApplicationDefinition>("ApplicationDefinitions");
                }
                return _ApplicationDefinitions;
            }
        }
        private ObjectSet<ApplicationDefinition> _ApplicationDefinitions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ApplicationEmail> ApplicationEmails
        {
            get
            {
                if ((_ApplicationEmails == null))
                {
                    _ApplicationEmails = base.CreateObjectSet<ApplicationEmail>("ApplicationEmails");
                }
                return _ApplicationEmails;
            }
        }
        private ObjectSet<ApplicationEmail> _ApplicationEmails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ApplicationEmailAccount> ApplicationEmailAccounts
        {
            get
            {
                if ((_ApplicationEmailAccounts == null))
                {
                    _ApplicationEmailAccounts = base.CreateObjectSet<ApplicationEmailAccount>("ApplicationEmailAccounts");
                }
                return _ApplicationEmailAccounts;
            }
        }
        private ObjectSet<ApplicationEmailAccount> _ApplicationEmailAccounts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ApplicationEmailAttachment> ApplicationEmailAttachments
        {
            get
            {
                if ((_ApplicationEmailAttachments == null))
                {
                    _ApplicationEmailAttachments = base.CreateObjectSet<ApplicationEmailAttachment>("ApplicationEmailAttachments");
                }
                return _ApplicationEmailAttachments;
            }
        }
        private ObjectSet<ApplicationEmailAttachment> _ApplicationEmailAttachments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ApplicationEmailEvent> ApplicationEmailEvents
        {
            get
            {
                if ((_ApplicationEmailEvents == null))
                {
                    _ApplicationEmailEvents = base.CreateObjectSet<ApplicationEmailEvent>("ApplicationEmailEvents");
                }
                return _ApplicationEmailEvents;
            }
        }
        private ObjectSet<ApplicationEmailEvent> _ApplicationEmailEvents;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserFileContents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserFileContents(UserFileContent userFileContent)
        {
            base.AddObject("UserFileContents", userFileContent);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BlockedEmails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBlockedEmails(BlockedEmail blockedEmail)
        {
            base.AddObject("BlockedEmails", blockedEmail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UsageAudits EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsageAudits(UsageAudit usageAudit)
        {
            base.AddObject("UsageAudits", usageAudit);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ApplicationDefinitions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToApplicationDefinitions(ApplicationDefinition applicationDefinition)
        {
            base.AddObject("ApplicationDefinitions", applicationDefinition);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ApplicationEmails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToApplicationEmails(ApplicationEmail applicationEmail)
        {
            base.AddObject("ApplicationEmails", applicationEmail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ApplicationEmailAccounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToApplicationEmailAccounts(ApplicationEmailAccount applicationEmailAccount)
        {
            base.AddObject("ApplicationEmailAccounts", applicationEmailAccount);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ApplicationEmailAttachments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToApplicationEmailAttachments(ApplicationEmailAttachment applicationEmailAttachment)
        {
            base.AddObject("ApplicationEmailAttachments", applicationEmailAttachment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ApplicationEmailEvents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToApplicationEmailEvents(ApplicationEmailEvent applicationEmailEvent)
        {
            base.AddObject("ApplicationEmailEvents", applicationEmailEvent);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FileStoreModel", Name="ApplicationDefinition")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ApplicationDefinition : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ApplicationDefinition object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static ApplicationDefinition CreateApplicationDefinition(global::System.Int32 id, global::System.String name)
        {
            ApplicationDefinition applicationDefinition = new ApplicationDefinition();
            applicationDefinition.Id = id;
            applicationDefinition.Name = name;
            return applicationDefinition;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FileStoreModel", "FK_ApplicationEmailAccount_ApplicationDefinition", "ApplicationEmailAccount")]
        public EntityCollection<ApplicationEmailAccount> ApplicationEmailAccounts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ApplicationEmailAccount>("FileStoreModel.FK_ApplicationEmailAccount_ApplicationDefinition", "ApplicationEmailAccount");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ApplicationEmailAccount>("FileStoreModel.FK_ApplicationEmailAccount_ApplicationDefinition", "ApplicationEmailAccount", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FileStoreModel", Name="ApplicationEmail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ApplicationEmail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ApplicationEmail object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="applicationEmailAccountId">Initial value of the ApplicationEmailAccountId property.</param>
        /// <param name="body">Initial value of the Body property.</param>
        /// <param name="htmlBody">Initial value of the HtmlBody property.</param>
        /// <param name="toList">Initial value of the ToList property.</param>
        /// <param name="createdDate">Initial value of the CreatedDate property.</param>
        public static ApplicationEmail CreateApplicationEmail(global::System.Int32 id, global::System.Int32 applicationEmailAccountId, global::System.String body, global::System.Boolean htmlBody, global::System.String toList, global::System.DateTime createdDate)
        {
            ApplicationEmail applicationEmail = new ApplicationEmail();
            applicationEmail.Id = id;
            applicationEmail.ApplicationEmailAccountId = applicationEmailAccountId;
            applicationEmail.Body = body;
            applicationEmail.HtmlBody = htmlBody;
            applicationEmail.ToList = toList;
            applicationEmail.CreatedDate = createdDate;
            return applicationEmail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ApplicationEmailAccountId
        {
            get
            {
                return _ApplicationEmailAccountId;
            }
            set
            {
                OnApplicationEmailAccountIdChanging(value);
                ReportPropertyChanging("ApplicationEmailAccountId");
                _ApplicationEmailAccountId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ApplicationEmailAccountId");
                OnApplicationEmailAccountIdChanged();
            }
        }
        private global::System.Int32 _ApplicationEmailAccountId;
        partial void OnApplicationEmailAccountIdChanging(global::System.Int32 value);
        partial void OnApplicationEmailAccountIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Body
        {
            get
            {
                return _Body;
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.String _Body;
        partial void OnBodyChanging(global::System.String value);
        partial void OnBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean HtmlBody
        {
            get
            {
                return _HtmlBody;
            }
            set
            {
                OnHtmlBodyChanging(value);
                ReportPropertyChanging("HtmlBody");
                _HtmlBody = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HtmlBody");
                OnHtmlBodyChanged();
            }
        }
        private global::System.Boolean _HtmlBody;
        partial void OnHtmlBodyChanging(global::System.Boolean value);
        partial void OnHtmlBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ToList
        {
            get
            {
                return _ToList;
            }
            set
            {
                OnToListChanging(value);
                ReportPropertyChanging("ToList");
                _ToList = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ToList");
                OnToListChanged();
            }
        }
        private global::System.String _ToList;
        partial void OnToListChanging(global::System.String value);
        partial void OnToListChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CCList
        {
            get
            {
                return _CCList;
            }
            set
            {
                OnCCListChanging(value);
                ReportPropertyChanging("CCList");
                _CCList = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CCList");
                OnCCListChanged();
            }
        }
        private global::System.String _CCList;
        partial void OnCCListChanging(global::System.String value);
        partial void OnCCListChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BCCList
        {
            get
            {
                return _BCCList;
            }
            set
            {
                OnBCCListChanging(value);
                ReportPropertyChanging("BCCList");
                _BCCList = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BCCList");
                OnBCCListChanged();
            }
        }
        private global::System.String _BCCList;
        partial void OnBCCListChanging(global::System.String value);
        partial void OnBCCListChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SentDate
        {
            get
            {
                return _SentDate;
            }
            set
            {
                OnSentDateChanging(value);
                ReportPropertyChanging("SentDate");
                _SentDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SentDate");
                OnSentDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _SentDate;
        partial void OnSentDateChanging(Nullable<global::System.DateTime> value);
        partial void OnSentDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> SentSuccessfully
        {
            get
            {
                return _SentSuccessfully;
            }
            set
            {
                OnSentSuccessfullyChanging(value);
                ReportPropertyChanging("SentSuccessfully");
                _SentSuccessfully = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SentSuccessfully");
                OnSentSuccessfullyChanged();
            }
        }
        private Nullable<global::System.Boolean> _SentSuccessfully;
        partial void OnSentSuccessfullyChanging(Nullable<global::System.Boolean> value);
        partial void OnSentSuccessfullyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ErrorMessage
        {
            get
            {
                return _ErrorMessage;
            }
            set
            {
                OnErrorMessageChanging(value);
                ReportPropertyChanging("ErrorMessage");
                _ErrorMessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ErrorMessage");
                OnErrorMessageChanged();
            }
        }
        private global::System.String _ErrorMessage;
        partial void OnErrorMessageChanging(global::System.String value);
        partial void OnErrorMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastResentDate
        {
            get
            {
                return _LastResentDate;
            }
            set
            {
                OnLastResentDateChanging(value);
                ReportPropertyChanging("LastResentDate");
                _LastResentDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastResentDate");
                OnLastResentDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastResentDate;
        partial void OnLastResentDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastResentDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ResendTriggered
        {
            get
            {
                return _ResendTriggered;
            }
            set
            {
                OnResendTriggeredChanging(value);
                ReportPropertyChanging("ResendTriggered");
                _ResendTriggered = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ResendTriggered");
                OnResendTriggeredChanged();
            }
        }
        private Nullable<global::System.Boolean> _ResendTriggered;
        partial void OnResendTriggeredChanging(Nullable<global::System.Boolean> value);
        partial void OnResendTriggeredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ResendTriggeredDate
        {
            get
            {
                return _ResendTriggeredDate;
            }
            set
            {
                OnResendTriggeredDateChanging(value);
                ReportPropertyChanging("ResendTriggeredDate");
                _ResendTriggeredDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ResendTriggeredDate");
                OnResendTriggeredDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ResendTriggeredDate;
        partial void OnResendTriggeredDateChanging(Nullable<global::System.DateTime> value);
        partial void OnResendTriggeredDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FileStoreModel", "FK_ApplicationEmailAttachment_ApplicationEmail", "ApplicationEmailAttachment")]
        public EntityCollection<ApplicationEmailAttachment> ApplicationEmailAttachments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ApplicationEmailAttachment>("FileStoreModel.FK_ApplicationEmailAttachment_ApplicationEmail", "ApplicationEmailAttachment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ApplicationEmailAttachment>("FileStoreModel.FK_ApplicationEmailAttachment_ApplicationEmail", "ApplicationEmailAttachment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FileStoreModel", "FK_ApplicationEmail_ApplicationEmailAccount", "ApplicationEmailAccount")]
        public ApplicationEmailAccount ApplicationEmailAccount
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationEmailAccount>("FileStoreModel.FK_ApplicationEmail_ApplicationEmailAccount", "ApplicationEmailAccount").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationEmailAccount>("FileStoreModel.FK_ApplicationEmail_ApplicationEmailAccount", "ApplicationEmailAccount").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ApplicationEmailAccount> ApplicationEmailAccountReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationEmailAccount>("FileStoreModel.FK_ApplicationEmail_ApplicationEmailAccount", "ApplicationEmailAccount");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ApplicationEmailAccount>("FileStoreModel.FK_ApplicationEmail_ApplicationEmailAccount", "ApplicationEmailAccount", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FileStoreModel", "FK_ApplicationEmailEvent_ApplicationEmail", "ApplicationEmailEvent")]
        public EntityCollection<ApplicationEmailEvent> ApplicationEmailEvents
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ApplicationEmailEvent>("FileStoreModel.FK_ApplicationEmailEvent_ApplicationEmail", "ApplicationEmailEvent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ApplicationEmailEvent>("FileStoreModel.FK_ApplicationEmailEvent_ApplicationEmail", "ApplicationEmailEvent", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FileStoreModel", Name="ApplicationEmailAccount")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ApplicationEmailAccount : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ApplicationEmailAccount object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="applicationDefinitionId">Initial value of the ApplicationDefinitionId property.</param>
        /// <param name="fromUserName">Initial value of the FromUserName property.</param>
        /// <param name="fromPassword">Initial value of the FromPassword property.</param>
        /// <param name="defaultAccount">Initial value of the DefaultAccount property.</param>
        public static ApplicationEmailAccount CreateApplicationEmailAccount(global::System.Int32 id, global::System.Int32 applicationDefinitionId, global::System.String fromUserName, global::System.String fromPassword, global::System.Boolean defaultAccount)
        {
            ApplicationEmailAccount applicationEmailAccount = new ApplicationEmailAccount();
            applicationEmailAccount.Id = id;
            applicationEmailAccount.ApplicationDefinitionId = applicationDefinitionId;
            applicationEmailAccount.FromUserName = fromUserName;
            applicationEmailAccount.FromPassword = fromPassword;
            applicationEmailAccount.DefaultAccount = defaultAccount;
            return applicationEmailAccount;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ApplicationDefinitionId
        {
            get
            {
                return _ApplicationDefinitionId;
            }
            set
            {
                OnApplicationDefinitionIdChanging(value);
                ReportPropertyChanging("ApplicationDefinitionId");
                _ApplicationDefinitionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ApplicationDefinitionId");
                OnApplicationDefinitionIdChanged();
            }
        }
        private global::System.Int32 _ApplicationDefinitionId;
        partial void OnApplicationDefinitionIdChanging(global::System.Int32 value);
        partial void OnApplicationDefinitionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SMTPAddress
        {
            get
            {
                return _SMTPAddress;
            }
            set
            {
                OnSMTPAddressChanging(value);
                ReportPropertyChanging("SMTPAddress");
                _SMTPAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SMTPAddress");
                OnSMTPAddressChanged();
            }
        }
        private global::System.String _SMTPAddress;
        partial void OnSMTPAddressChanging(global::System.String value);
        partial void OnSMTPAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SMTPPort
        {
            get
            {
                return _SMTPPort;
            }
            set
            {
                OnSMTPPortChanging(value);
                ReportPropertyChanging("SMTPPort");
                _SMTPPort = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SMTPPort");
                OnSMTPPortChanged();
            }
        }
        private Nullable<global::System.Int32> _SMTPPort;
        partial void OnSMTPPortChanging(Nullable<global::System.Int32> value);
        partial void OnSMTPPortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> EnableSsl
        {
            get
            {
                return _EnableSsl;
            }
            set
            {
                OnEnableSslChanging(value);
                ReportPropertyChanging("EnableSsl");
                _EnableSsl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EnableSsl");
                OnEnableSslChanged();
            }
        }
        private Nullable<global::System.Boolean> _EnableSsl;
        partial void OnEnableSslChanging(Nullable<global::System.Boolean> value);
        partial void OnEnableSslChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FromUserName
        {
            get
            {
                return _FromUserName;
            }
            set
            {
                OnFromUserNameChanging(value);
                ReportPropertyChanging("FromUserName");
                _FromUserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FromUserName");
                OnFromUserNameChanged();
            }
        }
        private global::System.String _FromUserName;
        partial void OnFromUserNameChanging(global::System.String value);
        partial void OnFromUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FromPassword
        {
            get
            {
                return _FromPassword;
            }
            set
            {
                OnFromPasswordChanging(value);
                ReportPropertyChanging("FromPassword");
                _FromPassword = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FromPassword");
                OnFromPasswordChanged();
            }
        }
        private global::System.String _FromPassword;
        partial void OnFromPasswordChanging(global::System.String value);
        partial void OnFromPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean DefaultAccount
        {
            get
            {
                return _DefaultAccount;
            }
            set
            {
                OnDefaultAccountChanging(value);
                ReportPropertyChanging("DefaultAccount");
                _DefaultAccount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DefaultAccount");
                OnDefaultAccountChanged();
            }
        }
        private global::System.Boolean _DefaultAccount;
        partial void OnDefaultAccountChanging(global::System.Boolean value);
        partial void OnDefaultAccountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DisplayName
        {
            get
            {
                return _DisplayName;
            }
            set
            {
                OnDisplayNameChanging(value);
                ReportPropertyChanging("DisplayName");
                _DisplayName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DisplayName");
                OnDisplayNameChanged();
            }
        }
        private global::System.String _DisplayName;
        partial void OnDisplayNameChanging(global::System.String value);
        partial void OnDisplayNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FileStoreModel", "FK_ApplicationEmailAccount_ApplicationDefinition", "ApplicationDefinition")]
        public ApplicationDefinition ApplicationDefinition
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationDefinition>("FileStoreModel.FK_ApplicationEmailAccount_ApplicationDefinition", "ApplicationDefinition").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationDefinition>("FileStoreModel.FK_ApplicationEmailAccount_ApplicationDefinition", "ApplicationDefinition").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ApplicationDefinition> ApplicationDefinitionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationDefinition>("FileStoreModel.FK_ApplicationEmailAccount_ApplicationDefinition", "ApplicationDefinition");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ApplicationDefinition>("FileStoreModel.FK_ApplicationEmailAccount_ApplicationDefinition", "ApplicationDefinition", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FileStoreModel", "FK_ApplicationEmail_ApplicationEmailAccount", "ApplicationEmail")]
        public EntityCollection<ApplicationEmail> ApplicationEmails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ApplicationEmail>("FileStoreModel.FK_ApplicationEmail_ApplicationEmailAccount", "ApplicationEmail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ApplicationEmail>("FileStoreModel.FK_ApplicationEmail_ApplicationEmailAccount", "ApplicationEmail", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FileStoreModel", Name="ApplicationEmailAttachment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ApplicationEmailAttachment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ApplicationEmailAttachment object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="applicationEmailId">Initial value of the ApplicationEmailId property.</param>
        /// <param name="fileName">Initial value of the FileName property.</param>
        /// <param name="fileContent">Initial value of the FileContent property.</param>
        /// <param name="extension">Initial value of the Extension property.</param>
        public static ApplicationEmailAttachment CreateApplicationEmailAttachment(global::System.Int32 id, global::System.Int32 applicationEmailId, global::System.String fileName, global::System.Byte[] fileContent, global::System.String extension)
        {
            ApplicationEmailAttachment applicationEmailAttachment = new ApplicationEmailAttachment();
            applicationEmailAttachment.Id = id;
            applicationEmailAttachment.ApplicationEmailId = applicationEmailId;
            applicationEmailAttachment.FileName = fileName;
            applicationEmailAttachment.FileContent = fileContent;
            applicationEmailAttachment.Extension = extension;
            return applicationEmailAttachment;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ApplicationEmailId
        {
            get
            {
                return _ApplicationEmailId;
            }
            set
            {
                OnApplicationEmailIdChanging(value);
                ReportPropertyChanging("ApplicationEmailId");
                _ApplicationEmailId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ApplicationEmailId");
                OnApplicationEmailIdChanged();
            }
        }
        private global::System.Int32 _ApplicationEmailId;
        partial void OnApplicationEmailIdChanging(global::System.Int32 value);
        partial void OnApplicationEmailIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] FileContent
        {
            get
            {
                return StructuralObject.GetValidValue(_FileContent);
            }
            set
            {
                OnFileContentChanging(value);
                ReportPropertyChanging("FileContent");
                _FileContent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileContent");
                OnFileContentChanged();
            }
        }
        private global::System.Byte[] _FileContent;
        partial void OnFileContentChanging(global::System.Byte[] value);
        partial void OnFileContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Extension
        {
            get
            {
                return _Extension;
            }
            set
            {
                OnExtensionChanging(value);
                ReportPropertyChanging("Extension");
                _Extension = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Extension");
                OnExtensionChanged();
            }
        }
        private global::System.String _Extension;
        partial void OnExtensionChanging(global::System.String value);
        partial void OnExtensionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FileStoreModel", "FK_ApplicationEmailAttachment_ApplicationEmail", "ApplicationEmail")]
        public ApplicationEmail ApplicationEmail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationEmail>("FileStoreModel.FK_ApplicationEmailAttachment_ApplicationEmail", "ApplicationEmail").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationEmail>("FileStoreModel.FK_ApplicationEmailAttachment_ApplicationEmail", "ApplicationEmail").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ApplicationEmail> ApplicationEmailReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationEmail>("FileStoreModel.FK_ApplicationEmailAttachment_ApplicationEmail", "ApplicationEmail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ApplicationEmail>("FileStoreModel.FK_ApplicationEmailAttachment_ApplicationEmail", "ApplicationEmail", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FileStoreModel", Name="ApplicationEmailEvent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ApplicationEmailEvent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ApplicationEmailEvent object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="applicationEmailId">Initial value of the ApplicationEmailId property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="eventId">Initial value of the EventId property.</param>
        public static ApplicationEmailEvent CreateApplicationEmailEvent(global::System.Int32 id, global::System.Int32 applicationEmailId, global::System.DateTime date, global::System.Int32 eventId)
        {
            ApplicationEmailEvent applicationEmailEvent = new ApplicationEmailEvent();
            applicationEmailEvent.Id = id;
            applicationEmailEvent.ApplicationEmailId = applicationEmailId;
            applicationEmailEvent.Date = date;
            applicationEmailEvent.EventId = eventId;
            return applicationEmailEvent;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ApplicationEmailId
        {
            get
            {
                return _ApplicationEmailId;
            }
            set
            {
                OnApplicationEmailIdChanging(value);
                ReportPropertyChanging("ApplicationEmailId");
                _ApplicationEmailId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ApplicationEmailId");
                OnApplicationEmailIdChanged();
            }
        }
        private global::System.Int32 _ApplicationEmailId;
        partial void OnApplicationEmailIdChanging(global::System.Int32 value);
        partial void OnApplicationEmailIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EventId
        {
            get
            {
                return _EventId;
            }
            set
            {
                OnEventIdChanging(value);
                ReportPropertyChanging("EventId");
                _EventId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventId");
                OnEventIdChanged();
            }
        }
        private global::System.Int32 _EventId;
        partial void OnEventIdChanging(global::System.Int32 value);
        partial void OnEventIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ErrorMessage
        {
            get
            {
                return _ErrorMessage;
            }
            set
            {
                OnErrorMessageChanging(value);
                ReportPropertyChanging("ErrorMessage");
                _ErrorMessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ErrorMessage");
                OnErrorMessageChanged();
            }
        }
        private global::System.String _ErrorMessage;
        partial void OnErrorMessageChanging(global::System.String value);
        partial void OnErrorMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ResendRequestedDate
        {
            get
            {
                return _ResendRequestedDate;
            }
            set
            {
                OnResendRequestedDateChanging(value);
                ReportPropertyChanging("ResendRequestedDate");
                _ResendRequestedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ResendRequestedDate");
                OnResendRequestedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ResendRequestedDate;
        partial void OnResendRequestedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnResendRequestedDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FileStoreModel", "FK_ApplicationEmailEvent_ApplicationEmail", "ApplicationEmail")]
        public ApplicationEmail ApplicationEmail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationEmail>("FileStoreModel.FK_ApplicationEmailEvent_ApplicationEmail", "ApplicationEmail").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationEmail>("FileStoreModel.FK_ApplicationEmailEvent_ApplicationEmail", "ApplicationEmail").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ApplicationEmail> ApplicationEmailReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationEmail>("FileStoreModel.FK_ApplicationEmailEvent_ApplicationEmail", "ApplicationEmail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ApplicationEmail>("FileStoreModel.FK_ApplicationEmailEvent_ApplicationEmail", "ApplicationEmail", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FileStoreModel", Name="BlockedEmail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BlockedEmail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BlockedEmail object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="emailAddress">Initial value of the EmailAddress property.</param>
        /// <param name="projectName">Initial value of the ProjectName property.</param>
        public static BlockedEmail CreateBlockedEmail(global::System.Int32 id, global::System.String emailAddress, global::System.String projectName)
        {
            BlockedEmail blockedEmail = new BlockedEmail();
            blockedEmail.Id = id;
            blockedEmail.EmailAddress = emailAddress;
            blockedEmail.ProjectName = projectName;
            return blockedEmail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProjectName
        {
            get
            {
                return _ProjectName;
            }
            set
            {
                OnProjectNameChanging(value);
                ReportPropertyChanging("ProjectName");
                _ProjectName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProjectName");
                OnProjectNameChanged();
            }
        }
        private global::System.String _ProjectName;
        partial void OnProjectNameChanging(global::System.String value);
        partial void OnProjectNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FileStoreModel", Name="UsageAudit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UsageAudit : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UsageAudit object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static UsageAudit CreateUsageAudit(global::System.Int32 id)
        {
            UsageAudit usageAudit = new UsageAudit();
            usageAudit.Id = id;
            return usageAudit;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CurrentExecutionFilePath
        {
            get
            {
                return _CurrentExecutionFilePath;
            }
            set
            {
                OnCurrentExecutionFilePathChanging(value);
                ReportPropertyChanging("CurrentExecutionFilePath");
                _CurrentExecutionFilePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CurrentExecutionFilePath");
                OnCurrentExecutionFilePathChanged();
            }
        }
        private global::System.String _CurrentExecutionFilePath;
        partial void OnCurrentExecutionFilePathChanging(global::System.String value);
        partial void OnCurrentExecutionFilePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhysicalApplicationPath
        {
            get
            {
                return _PhysicalApplicationPath;
            }
            set
            {
                OnPhysicalApplicationPathChanging(value);
                ReportPropertyChanging("PhysicalApplicationPath");
                _PhysicalApplicationPath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhysicalApplicationPath");
                OnPhysicalApplicationPathChanged();
            }
        }
        private global::System.String _PhysicalApplicationPath;
        partial void OnPhysicalApplicationPathChanging(global::System.String value);
        partial void OnPhysicalApplicationPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserAgent
        {
            get
            {
                return _UserAgent;
            }
            set
            {
                OnUserAgentChanging(value);
                ReportPropertyChanging("UserAgent");
                _UserAgent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserAgent");
                OnUserAgentChanged();
            }
        }
        private global::System.String _UserAgent;
        partial void OnUserAgentChanging(global::System.String value);
        partial void OnUserAgentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RemoteAddress
        {
            get
            {
                return _RemoteAddress;
            }
            set
            {
                OnRemoteAddressChanging(value);
                ReportPropertyChanging("RemoteAddress");
                _RemoteAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RemoteAddress");
                OnRemoteAddressChanged();
            }
        }
        private global::System.String _RemoteAddress;
        partial void OnRemoteAddressChanging(global::System.String value);
        partial void OnRemoteAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UrlReferrer
        {
            get
            {
                return _UrlReferrer;
            }
            set
            {
                OnUrlReferrerChanging(value);
                ReportPropertyChanging("UrlReferrer");
                _UrlReferrer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UrlReferrer");
                OnUrlReferrerChanged();
            }
        }
        private global::System.String _UrlReferrer;
        partial void OnUrlReferrerChanging(global::System.String value);
        partial void OnUrlReferrerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LogonUser
        {
            get
            {
                return _LogonUser;
            }
            set
            {
                OnLogonUserChanging(value);
                ReportPropertyChanging("LogonUser");
                _LogonUser = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LogonUser");
                OnLogonUserChanged();
            }
        }
        private global::System.String _LogonUser;
        partial void OnLogonUserChanging(global::System.String value);
        partial void OnLogonUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HttpHost
        {
            get
            {
                return _HttpHost;
            }
            set
            {
                OnHttpHostChanging(value);
                ReportPropertyChanging("HttpHost");
                _HttpHost = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HttpHost");
                OnHttpHostChanged();
            }
        }
        private global::System.String _HttpHost;
        partial void OnHttpHostChanging(global::System.String value);
        partial void OnHttpHostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MachineName
        {
            get
            {
                return _MachineName;
            }
            set
            {
                OnMachineNameChanging(value);
                ReportPropertyChanging("MachineName");
                _MachineName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MachineName");
                OnMachineNameChanged();
            }
        }
        private global::System.String _MachineName;
        partial void OnMachineNameChanging(global::System.String value);
        partial void OnMachineNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FileStoreModel", Name="UserFileContent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserFileContent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserFileContent object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="projectName">Initial value of the ProjectName property.</param>
        /// <param name="path">Initial value of the Path property.</param>
        /// <param name="fileName">Initial value of the FileName property.</param>
        /// <param name="file">Initial value of the File property.</param>
        /// <param name="createdDateTime">Initial value of the CreatedDateTime property.</param>
        public static UserFileContent CreateUserFileContent(global::System.Int32 id, global::System.String projectName, global::System.String path, global::System.String fileName, global::System.Byte[] file, global::System.DateTime createdDateTime)
        {
            UserFileContent userFileContent = new UserFileContent();
            userFileContent.Id = id;
            userFileContent.ProjectName = projectName;
            userFileContent.Path = path;
            userFileContent.FileName = fileName;
            userFileContent.File = file;
            userFileContent.CreatedDateTime = createdDateTime;
            return userFileContent;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProjectName
        {
            get
            {
                return _ProjectName;
            }
            set
            {
                OnProjectNameChanging(value);
                ReportPropertyChanging("ProjectName");
                _ProjectName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProjectName");
                OnProjectNameChanged();
            }
        }
        private global::System.String _ProjectName;
        partial void OnProjectNameChanging(global::System.String value);
        partial void OnProjectNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Path
        {
            get
            {
                return _Path;
            }
            set
            {
                OnPathChanging(value);
                ReportPropertyChanging("Path");
                _Path = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Path");
                OnPathChanged();
            }
        }
        private global::System.String _Path;
        partial void OnPathChanging(global::System.String value);
        partial void OnPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] File
        {
            get
            {
                return StructuralObject.GetValidValue(_File);
            }
            set
            {
                OnFileChanging(value);
                ReportPropertyChanging("File");
                _File = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("File");
                OnFileChanged();
            }
        }
        private global::System.Byte[] _File;
        partial void OnFileChanging(global::System.Byte[] value);
        partial void OnFileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private global::System.DateTime _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTime value);
        partial void OnCreatedDateTimeChanged();

        #endregion

    
    }

    #endregion

    
}
